spring:
  data:
    mongodb:
      username: aaa
      password: "123456"
      host: 47.103.22.170
      port: 27017
      database: test
  rabbitmq:
    host: 47.103.22.170
    port: 5672
    virtual-host: /
    username: guest
    password: guest
server:
  port: 8080


